// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkCZChF-ibj9GqOaXzN1RgEOOEhWV6yqg',
    appId: '1:579274906518:web:8625e764d183dd6cdd9bb7',
    messagingSenderId: '579274906518',
    projectId: 'nobetci-eczane-7c0d4',
    authDomain: 'nobetci-eczane-7c0d4.firebaseapp.com',
    databaseURL: 'https://nobetci-eczane-7c0d4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nobetci-eczane-7c0d4.firebasestorage.app',
    measurementId: 'G-D6MV1H0JJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLzLwmy6ziepWZlKeWHaUVgbfEM-Xzd9I',
    appId: '1:579274906518:android:9390180e794a0ef8dd9bb7',
    messagingSenderId: '579274906518',
    projectId: 'nobetci-eczane-7c0d4',
    databaseURL: 'https://nobetci-eczane-7c0d4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nobetci-eczane-7c0d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHnVBUS_XUSu7hifdYY-bu6vrgE1ypuzw',
    appId: '1:579274906518:ios:19710901a41d48cadd9bb7',
    messagingSenderId: '579274906518',
    projectId: 'nobetci-eczane-7c0d4',
    databaseURL: 'https://nobetci-eczane-7c0d4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nobetci-eczane-7c0d4.firebasestorage.app',
    iosBundleId: 'com.example.eczaneVs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHnVBUS_XUSu7hifdYY-bu6vrgE1ypuzw',
    appId: '1:579274906518:ios:19710901a41d48cadd9bb7',
    messagingSenderId: '579274906518',
    projectId: 'nobetci-eczane-7c0d4',
    databaseURL: 'https://nobetci-eczane-7c0d4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nobetci-eczane-7c0d4.firebasestorage.app',
    iosBundleId: 'com.example.eczaneVs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkCZChF-ibj9GqOaXzN1RgEOOEhWV6yqg',
    appId: '1:579274906518:web:f92e54ab7e2f1bdedd9bb7',
    messagingSenderId: '579274906518',
    projectId: 'nobetci-eczane-7c0d4',
    authDomain: 'nobetci-eczane-7c0d4.firebaseapp.com',
    databaseURL: 'https://nobetci-eczane-7c0d4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nobetci-eczane-7c0d4.firebasestorage.app',
    measurementId: 'G-7BVRV7V1CJ',
  );
}
